version: '3.9'

services:
  db:
    container_name: internal_notes_db_container
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: internal_notes
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - internal_notes_network  
  api:
    container_name: internal_notes
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "npm run typeorm migration:run && npm run start"
    volumes:
      - ./build:/usr/src/internal_notes_v1/build
    ports:
      - 3333:3333
    networks:
      - internal_notes_network
    depends_on:
      - db  
networks:
  internal_notes_network:
    driver: bridge 
volumes:
  data:
    driver: local
