version: '3'

services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: internal_notes
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - notes  
  api:
    container_name: internal_notes
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./build:/usr/src/internal_notes_v1/build
    ports:
      - 3333:3333
    networks:
      - notes  
    depends_on:
      - db  
networks:
  notes: