version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: internal_notes
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data